name: The Green Microcycle
favicon: null
layout_spectrum: 0
typography_spectrum: 0.04095143429003656
title: "The Electric Bicycle That's Also A Pedal Generator"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00001c'
    - '#b9d7cb'
    - '#8b9d9d'
    - '#785f5a'
    - '#1b8137'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
