name: The Green Microcycle Plus
favicon: null
layout_spectrum: 1
typography_spectrum: 0.04095143429003656
title: "The Electric Bicycle That's Also A Pedal Generator"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c1139'
    - '#ad9d84'
    - '#43839c'
    - '#afea1e'
    - '#fcffa4'
  brandStrength: 0.6875
  lightness: 0.5794796925038099
  saturation: 0.8905803617089987
  rhythmicContrast: 0.3028224497102201
purpose: []
